### ISSUE TITLE
TODO List for Dynamic Walking 2015 paper

### ISSUE THREAD

**Issue by naveenoid** [jeljaik/extended-kalman-filter#7]
# Extended Abstract TODO
- [ ] Abstract sections update
- [ ] Photographs of Balancing, sensorized skin image
# Technical Work TODO
- [ ] Contact Diego Torazza, RBCS Mechanical Design head Robotics, Brain and Cognitive Sciences for new 3D printed foot.
- [ ] Gyroscope status and timetable verify with Maggiali and Nori
- [ ] Review Kalman Filters libraries and pick best
- [ ] Consider scalable design of library fitting inside yarpWholeBodyState
# Theoretical Work TODO#
- [ ]  Dani on stability analysis of existing controller (maybe with assumptions on error bounds of sensors?)
- [ ] Expand model to consider a compliant contact with world?

**Comment by jeljaik** [comment]
TODO List After 19-03-2015 Meeting
- [ ] 1. Proper computation of f_0, mu_o from hip F/T sensors.
- [ ] 2. Data gathering and tests with this data.
- [ ] 3. Improved estimation of Q and R .
- [ ] 4. Add compliance to state dynamics.
- [ ] 5. Adaptive EKF version of the IROS paper. 
- [ ] 5\* Adaptive Kalman Filter research.
- [ ] 6. Estimation of gyro bias as part of the state.
- [ ] 7. Expand IROS paper work with quaternions.
- [ ] 8*. C++ Implementation of the IROS paper.
- [ ] 8. C++ implementation for Dynamic Walking 2015.
- [ ] 9. Integration with balancing.
- [ ] 10. Balancing demo.
- [ ] 11. HUMANOIDS paper.
