### ISSUE TITLE
Quaternion-based Orientation Estimation

### ISSUE THREAD

**Issue by jeljaik** [jeljaik/extended-kalman-filter#9]
**CURRENTLY** working on it. Very very soon pushing initial code and brief report describing the method.
# TODO List
- [x] Write 3D visualizer.
- [ ] Write summary on Quest Attitude Determination.
- [x] Write model function.
- [x] Write measurement derivative function.
- [x] Finish coding simplified version of the quaternion-based EKF.
- [x] Push code when first full skeleton is ready.
- [x] Notes on theory and implementation.
- [ ] Update website with the first corrected draft version of my notes.
- [ ] Unify notation.
- [x] Online estimation with visualization

**Comment by jeljaik** [comment]
First perfectly working version in https://github.com/jeljaik/extended-kalman-filter/commit/80f34407bf7da10ff5981be1d5ba43afcfbf0e6e

e.g. `mainVisualizer('batchEKF', 'fullPitchRotation.mat', [])`

**Comment by jeljaik** [comment]
Visualization of a full pitch rotations without singularities. 

![fullpitch](https://cloud.githubusercontent.com/assets/5030039/6710862/bc8e0d20-cd83-11e4-96b3-f377b42c68c7.png)

**Comment by naveenoid** [comment]
Excellent work @jeljaik

---

Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy
